# Generated by Django 4.1.1 on 2022-10-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dateOfJoining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
