# Generated by Django 4.1.1 on 2022-10-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('quizScore_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quiz_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.quizzes')),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
        ),
    ]
