# Generated by Django 4.1.1 on 2022-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enrollments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Course Category'},
        ),
        migrations.AlterModelOptions(
            name='coursepdf',
            options={'verbose_name_plural': 'CoursePDF'},
        ),
        migrations.AlterModelOptions(
            name='coursevideo',
            options={'verbose_name': 'Course Video'},
        ),
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'verbose_name': 'Quiz Score'},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'verbose_name': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='videoinfo',
            options={'verbose_name': 'Video Info'},
        ),
    ]
