# Generated by Django 4.1.1 on 2022-12-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_options_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Speciality',
            field=models.CharField(default='Teacher', max_length=150),
        ),
    ]
