# Generated by Django 4.1.1 on 2022-12-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Speciality',
            new_name='speciality',
        ),
    ]
