# Generated by Django 4.1.1 on 2022-12-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_speciality_teacher_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='feature_img',
            field=models.ImageField(default=None, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
