# Generated by Django 4.1.1 on 2022-12-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
