# Generated by Django 4.1.1 on 2022-12-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feature_img',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
    ]
