# Generated by Django 4.1.1 on 2022-12-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_course_feature_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(default='None', max_length=50),
        ),
    ]
