# Generated by Django 4.1.1 on 2022-12-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_course_chapter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='course_title',
            new_name='course',
        ),
    ]
