# Generated by Django 4.1.1 on 2022-12-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_course_title_chapter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
