# Generated by Django 4.1.1 on 2023-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
