# Generated by Django 4.1.1 on 2023-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_teacher_bio_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='None', max_length=400),
        ),
    ]
