# Generated by Django 4.1.1 on 2023-01-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_course_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='student_id',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='main.course'),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='main.students'),
        ),
    ]
