# Generated by Django 4.1.1 on 2023-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_enrollments_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_description',
            field=models.TextField(default='None', max_length=300),
        ),
    ]
