# Generated by Django 4.1.1 on 2023-01-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ImageField(null=True, upload_to='teacher_images/'),
        ),
    ]
