# Generated by Django 4.1.1 on 2023-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_teacher_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_profile',
            field=models.ImageField(null=True, upload_to='teacher_profile_images/'),
        ),
    ]
