# Generated by Django 4.1.1 on 2023-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='interested_categories',
            field=models.TextField(default='None', max_length=150),
        ),
    ]
