# Generated by Django 4.1.1 on 2023-01-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_studentassignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
