# Generated by Django 4.1.1 on 2023-01-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_status_studentassignment_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_text', models.TextField(default=None, max_length=200)),
                ('notif_for', models.CharField(default=None, max_length=200)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
