# Generated by Django 4.1.1 on 2023-01-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_notification_alter_students_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
    ]
