# Generated by Django 4.1.1 on 2023-01-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_notification_notif_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
