# Generated by Django 4.1.1 on 2023-01-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_notification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_subject',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
