# Generated by Django 4.1.1 on 2023-01-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_quizzes_teacher_quizzesquestions_coursequize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseQuize',
            new_name='CourseQuiz',
        ),
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name': 'Course Quiz'},
        ),
    ]
