# Generated by Django 4.1.1 on 2023-01-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_coursequize_coursequiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='coursequiz',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizzes'),
        ),
    ]
