# Generated by Django 4.1.1 on 2023-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_attemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='correct_answer',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
