# Generated by Django 4.1.1 on 2023-02-05 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_attemptquestion_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('description', models.TextField(default='None', max_length=300)),
                ('files', models.FileField(null=True, upload_to='study_materials/')),
                ('remarks', models.TextField(default='None', max_length=150)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name': 'Course Study Materials',
            },
        ),
    ]
