# Generated by Django 4.1.1 on 2023-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_course_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
