# Generated by Django 4.1.1 on 2023-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
