# Generated by Django 4.1.1 on 2023-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_faq_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default='None', max_length=300),
        ),
    ]
