# Generated by Django 4.1.1 on 2023-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_remove_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
