# Generated by Django 4.1.1 on 2023-03-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
